#!/bin/bash

array=("bash_aliases" "bash_history" "bash_profile" "bashrc" "profile" "screenrc" "vimrc")

for i in "${array[@]}"
do
    ln -sf ~/dotfiles_linux/$i ~/.$i
done

ln -sf ~/dotfiles_linux/sshconfig ~/.ssh/config
